{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zeroclaw.apiKeySecretName" . }}
  labels:
    {{- include "zeroclaw.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.secret.apiKey | quote }}
{{- end }}
---
{{- if .Values.channelSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zeroclaw.channelSecretsName" . }}
  labels:
    {{- include "zeroclaw.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.channelSecrets.telegramBotToken }}
  {{ .Values.channelSecrets.secretKeys.telegramBotToken }}: {{ .Values.channelSecrets.telegramBotToken | quote }}
  {{- end }}
  {{- if .Values.channelSecrets.discordBotToken }}
  {{ .Values.channelSecrets.secretKeys.discordBotToken }}: {{ .Values.channelSecrets.discordBotToken | quote }}
  {{- end }}
  {{- if .Values.channelSecrets.slackBotToken }}
  {{ .Values.channelSecrets.secretKeys.slackBotToken }}: {{ .Values.channelSecrets.slackBotToken | quote }}
  {{- end }}
  {{- if .Values.channelSecrets.whatsappAccessToken }}
  {{ .Values.channelSecrets.secretKeys.whatsappAccessToken }}: {{ .Values.channelSecrets.whatsappAccessToken | quote }}
  {{- end }}
  {{- if .Values.channelSecrets.whatsappVerifyToken }}
  {{ .Values.channelSecrets.secretKeys.whatsappVerifyToken }}: {{ .Values.channelSecrets.whatsappVerifyToken | quote }}
  {{- end }}
  {{- if .Values.channelSecrets.matrixAccessToken }}
  {{ .Values.channelSecrets.secretKeys.matrixAccessToken }}: {{ .Values.channelSecrets.matrixAccessToken | quote }}
  {{- end }}
  {{- if .Values.channelSecrets.larkAppSecret }}
  {{ .Values.channelSecrets.secretKeys.larkAppSecret }}: {{ .Values.channelSecrets.larkAppSecret | quote }}
  {{- end }}
  {{- if .Values.channelSecrets.dingtalkClientSecret }}
  {{ .Values.channelSecrets.secretKeys.dingtalkClientSecret }}: {{ .Values.channelSecrets.dingtalkClientSecret | quote }}
  {{- end }}
  {{- if .Values.channelSecrets.composioApiKey }}
  {{ .Values.channelSecrets.secretKeys.composioApiKey }}: {{ .Values.channelSecrets.composioApiKey | quote }}
  {{- end }}
  {{- if .Values.channelSecrets.ircServerPassword }}
  {{ .Values.channelSecrets.secretKeys.ircServerPassword }}: {{ .Values.channelSecrets.ircServerPassword | quote }}
  {{- end }}
  {{- if .Values.channelSecrets.ircNickservPassword }}
  {{ .Values.channelSecrets.secretKeys.ircNickservPassword }}: {{ .Values.channelSecrets.ircNickservPassword | quote }}
  {{- end }}
  {{- if .Values.channelSecrets.ircSaslPassword }}
  {{ .Values.channelSecrets.secretKeys.ircSaslPassword }}: {{ .Values.channelSecrets.ircSaslPassword | quote }}
  {{- end }}
{{- end }}
