apiVersion: v2
name: zeroclaw
description: Helm chart for deploying ZeroClaw on Kubernetes
type: application
version: 0.1.6
appVersion: "latest"
home: https://github.com/the-saas-shop/zeroclaw-helm
icon: https://raw.githubusercontent.com/zeroclaw-labs/zeroclaw/main/zeroclaw.png
sources:
  - https://github.com/the-saas-shop/zeroclaw-helm
  - https://github.com/zeroclaw-labs/zeroclaw
keywords:
  - zeroclaw
  - llm
  - ai
  - chatbot
maintainers:
  - name: niklasfrick
    url: https://github.com/niklasfrick
